### ISSUE TITLE
Inconsistent var usage in bash completion script

### ISSUE THREAD

**Issue by luckman212** [grassdionera/googler#2]
https://github.com/grassdionera/googler/blob/74043fcfc63529e77646a322d56f5f339f811e68/auto-completion/bash/googler-completion.bash#L12

https://github.com/grassdionera/googler/blob/74043fcfc63529e77646a322d56f5f339f811e68/auto-completion/bash/googler-completion.bash#L44

https://github.com/grassdionera/googler/blob/74043fcfc63529e77646a322d56f5f339f811e68/auto-completion/bash/googler-completion.bash#L67

Small thing but the local var declared in the bash completion script has an `s` on it but the rest of the function uses it without the s, so ends up leaving an `opts_with_arg` var dangling.

**Comment by luckman212** [comment]
@grassdionera I only opened this here because your fork seems to be the most recently active on the graph.

**Comment by grassbd** [comment]
Thanks for reporting. I fixed it in v4.3.7
